enum BlockActionType {
	GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST",
	GET_NOTIFICATION_SUCCEEDED = "GET_NOTIFICATION_SUCCEEDED",
	GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED",
	POST_NOTIFICATION_REQUEST = "POST_NOTIFICATION_REQUEST",
	POST_NOTIFICATION_SUCCEEDED = "POST_NOTIFICATION_SUCCEEDED",
	POST_NOTIFICATION_FAILED = "POST_NOTIFICATION_FAILED",
	PATCH_NOTIFICATION_REQUEST = "PATCH_NOTIFICATION_REQUEST",
	PATCH_NOTIFICATION_SUCCEEDED = "PATCH_NOTIFICATION_SUCCEEDED",
	PATCH_NOTIFICATION_FAILED = "PATCH_NOTIFICATION_FAILED",
	DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST",
	DELETE_NOTIFICATION_SUCCEEDED = "DELETE_NOTIFICATION_SUCCEEDED",
	DELETE_NOTIFICATION_FAILED = "DELETE_NOTIFICATION_FAILED",
}

export default BlockActionType;
