enum PressReleasePublishActionType {

	GET_PRESS_RELEASE_PUBLISH_REQUEST = "GET_PRESS_RELEASE_PUBLISH_REQUEST",
	GET_PRESS_RELEASE_PUBLISH_SUCCEEDED = "GET_PRESS_RELEASE_PUBLISH_SUCCEEDED",
	GET_PRESS_RELEASE_PUBLISH_FAILED = "GET_PRESS_RELEASE_PUBLISH_FAILED",

	POST_PRESS_RELEASE_PUBLISH_REQUEST = "POST_PRESS_RELEASE_PUBLISH_REQUEST",
	POST_PRESS_RELEASE_PUBLISH_SUCCEEDED = "POST_PRESS_RELEASE_PUBLISH_SUCCEEDED",
	POST_PRESS_RELEASE_PUBLISH_FAILED = "POST_PRESS_RELEASE_PUBLISH_FAILED",

	SET_PRESS_RELEASE_PUBLISH = "SET_PRESS_RELEASE_PUBLISH_FAILED",

	GET_PRESS_RELEASE_OGP_REQUEST = "GET_PRESS_RELEASE_OGP_REQUEST",
	GET_PRESS_RELEASE_OGP_SUCCEEDED = "GET_PRESS_RELEASE_OGP_SUCCEEDED",
	GET_PRESS_RELEASE_OGP_FAILED = "GET_PRESS_RELEASE_OGP_FAILED",

	POST_PRESS_RELEASE_OGP_REQUEST = "POST_PRESS_RELEASE_OGP_REQUEST",
	POST_PRESS_RELEASE_OGP_SUCCEEDED = "POST_PRESS_RELEASE_OGP_SUCCEEDED",
	POST_PRESS_RELEASE_OGP_FAILED = "POST_PRESS_RELEASE_OGP_FAILED",

	SET_PRESS_RELEASE_OGP = "SET_PRESS_RELEASE_OGP_FAILED",

}

export default PressReleasePublishActionType

