enum PressKitActionType {
	GET_PRESS_KIT_LIST_REQUEST = "GET_PRESS_KIT_LIST_REQUEST",
	GET_PRESS_KIT_LIST_SUCCEEDED = "GET_PRESS_KIT_LIST_SUCCEEDED",
	GET_PRESS_KIT_LIST_FAILED = "GET_PRESS_KIT_LIST_FAILED",

	GET_PRESS_KIT_DETAILS_REQUEST = "GET_PRESS_KIT_DETAILS_REQUEST",
	GET_PRESS_KIT_DETAILS_SUCCEEDED = "GET_PRESS_KIT_DETAILS_SUCCEEDED",
	GET_PRESS_KIT_DETAILS_FAILED = "GET_PRESS_KIT_DETAILS_FAILED",

	POST_PRESS_KIT_DETAILS_REQUEST = "POST_PRESS_KIT_DETAILS_REQUEST",
	POST_PRESS_KIT_DETAILS_SUCCEEDED = "POST_PRESS_KIT_DETAILS_SUCCEEDED",
	POST_PRESS_KIT_DETAILS_FAILED = "POST_PRESS_KIT_DETAILS_FAILED",

	PATCH_PRESS_KIT_DETAILS_REQUEST = "PATCH_PRESS_KIT_DETAILS_REQUEST",
	PATCH_PRESS_KIT_DETAILS_SUCCEEDED = "PATCH_PRESS_KIT_DETAILS_SUCCEEDED",
	PATCH_PRESS_KIT_DETAILS_FAILED = "PATCH_PRESS_KIT_DETAILS_FAILED",

	DELETE_PRESS_KIT_DETAILS_REQUEST = "DELETE_PRESS_KIT_DETAILS_REQUEST",
	DELETE_PRESS_KIT_DETAILS_SUCCEEDED = "DELETE_PRESS_KIT_DETAILS_SUCCEEDED",
	DELETE_PRESS_KIT_DETAILS_FAILED = "DELETE_PRESS_KIT_DETAILS_FAILED",

	SET_PRESS_KIT_DETAILS = "SET_PRESS_KIT_DETAILS",

	SET_PRESS_KIT_NAME = "SET_PRESS_KIT_NAME",

	PATCH_PRESS_KIT_NAME_REQUEST = "PATCH_PRESS_KIT_NAME_REQUEST",
	PATCH_PRESS_KIT_NAME_SUCCEEDED = "PATCH_PRESS_KIT_NAME_SUCCEEDED",
	PATCH_PRESS_KIT_NAME_FAILED = "PATCH_PRESS_KIT_NAME_FAILED",

	POST_PRESS_KIT_CLONE_REQUEST = "POST_PRESS_KIT_CLONE_REQUEST",
	POST_PRESS_KIT_CLONE_SUCCEEDED = "POST_PRESS_KIT_CLONE_SUCCEEDED",
	POST_PRESS_KIT_CLONE_FAILED = "POST_PRESS_KIT_CLONE_FAILED",

	PATCH_PRESS_KIT_ARCHIVE_REQUEST = "PATCH_PRESS_KIT_ARCHIVE_REQUEST",
	PATCH_PRESS_KIT_ARCHIVE_SUCCEEDED = "PATCH_PRESS_KIT_ARCHIVE_SUCCEEDED",
	PATCH_PRESS_KIT_ARCHIVE_FAILED = "PATCH_PRESS_KIT_ARCHIVE_FAILED",

	SET_PRESS_KIT_CREATE_DIALOG = "SET_PRESS_KIT_CREATE_DIALOG",
	SET_PRESS_KIT_TEMPLATE = "SET_PRESS_KIT_TEMPLATE",

	GET_PRESS_KIT_TEMPLATE_REQUEST = "GET_PRESS_KIT_TEMPLATE_REQUEST",
	GET_PRESS_KIT_TEMPLATE_SUCCEEDED = "GET_PRESS_KIT_TEMPLATE_SUCCEEDED",
	GET_PRESS_KIT_TEMPLATE_FAILED = "GET_PRESS_KIT_TEMPLATE_FAILED",

	GET_PRESS_KIT_TEMPLATE_LIST_REQUEST = "GET_PRESS_KIT_TEMPLATE_LIST_REQUEST",
	GET_PRESS_KIT_TEMPLATE_LIST_SUCCEEDED = "GET_PRESS_KIT_TEMPLATE_LIST_SUCCEEDED",
	GET_PRESS_KIT_TEMPLATE_LIST_FAILED = "GET_PRESS_KIT_TEMPLATE_LIST_FAILED",}

export default PressKitActionType
