enum MediaActionType {
	GET_MEDIA_LIST_REQUEST = "GET_MEDIA_LIST_REQUEST",
	GET_MEDIA_LIST_SUCCEEDED = "GET_MEDIA_LIST_SUCCEEDED",
	GET_MEDIA_LIST_FAILED = "GET_MEDIA_LIST_FAILED",

	GET_MEDIA_ALL_LIST_REQUEST = "GET_MEDIA_ALL_LIST_REQUEST",
	GET_MEDIA_ALL_LIST_SUCCEEDED = "GET_MEDIA_ALL_LIST_SUCCEEDED",
	GET_MEDIA_ALL_LIST_FAILED = "GET_MEDIA_ALL_LIST_FAILED",

	GET_MEDIA_DETAIL_REQUEST = "GET_MEDIA_DETAIL_REQUEST",
	GET_MEDIA_DETAIL_SUCCEEDED = "GET_MEDIA_DETAIL_SUCCEEDED",
	GET_MEDIA_DETAIL_FAILED = "GET_MEDIA_DETAIL_FAILED",
	POST_MEDIA_REQUEST = "POST_MEDIA_REQUEST",
	POST_MEDIA_SUCCEEDED = "POST_MEDIA_SUCCEEDED",
	POST_MEDIA_FAILED = "POST_MEDIA_FAILED",
	PATCH_MEDIA_REQUEST = "PATCH_MEDIA_REQUEST",
	PATCH_MEDIA_SUCCEEDED = "PATCH_MEDIA_SUCCEEDED",
	PATCH_MEDIA_FAILED = "PATCH_MEDIA_FAILED",
	DELETE_MEDIA_REQUEST = "DELETE_MEDIA_REQUEST",
	DELETE_MEDIA_SUCCEEDED = "DELETE_MEDIA_SUCCEEDED",
	DELETE_MEDIA_FAILED = "DELETE_MEDIA_FAILED",


}

export default MediaActionType;
