enum SignActionType {
	POST_SIGN_UP_REQUEST = "POST_SIGN_UP_REQUEST",
    POST_SIGN_UP_SUCCEEDED = "POST_SIGN_UP_SUCCEEDED",
    POST_SIGN_UP_FAILED = "POST_SIGN_UP_FAILED",

	GET_SIGN_UP_ACTIVATE_REQUEST = "GET_SIGN_UP_ACTIVATE_REQUEST",
	GET_SIGN_UP_ACTIVATE_SUCCEEDED = "GET_SIGN_UP_ACTIVATE_SUCCEEDED",
	GET_SIGN_UP_ACTIVATE_FAILED = "GET_SIGN_UP_ACTIVATE_FAILED",

	POST_SIGN_IN_REQUEST = "POST_SIGN_IN_REQUEST",
	POST_SIGN_IN_SUCCEEDED = "POST_SIGN_IN_SUCCEEDED",
	POST_SIGN_IN_FAILED = "POST_SIGN_IN_FAILED",
}

export default SignActionType;

