enum PressReleaseReserveActionType {

	POST_PRESS_RELEASE_MEDIA_RECOMMEND_REQUEST = "POST_PRESS_RELEASE_MEDIA_RECOMMEND_REQUEST",
	POST_PRESS_RELEASE_MEDIA_RECOMMEND_SUCCEEDED = "POST_PRESS_RELEASE_MEDIA_RECOMMEND_SUCCEEDED",
	POST_PRESS_RELEASE_MEDIA_RECOMMEND_FAILED = "POST_PRESS_RELEASE_MEDIA_RECOMMEND_FAILED",

	GET_PRESS_RELEASE_CUSTOM_MEDIA_REQUEST = "GET_PRESS_RELEASE_CUSTOM_MEDIA_REQUEST",
	GET_PRESS_RELEASE_CUSTOM_MEDIA_SUCCEEDED = "GET_PRESS_RELEASE_CUSTOM_MEDIA_SUCCEEDED",
	GET_PRESS_RELEASE_CUSTOM_MEDIA_FAILED = "GET_PRESS_RELEASE_CUSTOM_MEDIA_FAILED",

	GET_PRESS_RELEASE_AUTO_MEDIA_REQUEST = "GET_PRESS_RELEASE_AUTO_MEDIA_REQUEST",
	GET_PRESS_RELEASE_AUTO_MEDIA_SUCCEEDED = "GET_PRESS_RELEASE_AUTO_MEDIA_SUCCEEDED",
	GET_PRESS_RELEASE_AUTO_MEDIA_FAILED = "GET_PRESS_RELEASE_AUTO_MEDIA_FAILED",

	GET_PRESS_RELEASE_RESERVE_REQUEST = "GET_PRESS_RELEASE_RESERVE_REQUEST",
	GET_PRESS_RELEASE_RESERVE_SUCCEEDED = "GET_PRESS_RELEASE_RESERVE_SUCCEEDED",
	GET_PRESS_RELEASE_RESERVE_FAILED = "GET_PRESS_RELEASE_RESERVE_FAILED",

	POST_PRESS_RELEASE_RESERVE_REQUEST = "POST_PRESS_RELEASE_RESERVE_REQUEST",
	POST_PRESS_RELEASE_RESERVE_SUCCEEDED = "POST_PRESS_RELEASE_RESERVE_SUCCEEDED",
	POST_PRESS_RELEASE_RESERVE_FAILED = "POST_PRESS_RELEASE_RESERVE_FAILED",

	DELETE_PRESS_RELEASE_RESERVE_REQUEST = "DELETE_PRESS_RELEASE_RESERVE_REQUEST",
	DELETE_PRESS_RELEASE_RESERVE_SUCCEEDED = "DELETE_PRESS_RELEASE_RESERVE_SUCCEEDED",
	DELETE_PRESS_RELEASE_RESERVE_FAILED = "DELETE_PRESS_RELEASE_RESERVE_FAILED",

	SET_PRESS_RELEASE_RESERVE_CUSTOM = "SET_PRESS_RELEASE_RESERVE_CUSTOM",
    SET_PRESS_RELEASE_RESERVE_COPY = "SET_PRESS_RELEASE_RESERVE_COPY",
	SET_PRESS_RELEASE_RESERVE_AUTO = "SET_PRESS_RELEASE_RESERVE_AUTO",
	SET_PRESS_RELEASE_RESERVE_DATETIME = "SET_PRESS_RELEASE_RESERVE_DATETIME",
	SET_PRESS_RELEASE_RESERVE_ACTIVE = "SET_PRESS_RELEASE_RESERVE_ACTIVE",
	SET_PRESS_RELEASE_RESERVE_REVIEW = "SET_PRESS_RELEASE_RESERVE_REVIEW",

	POST_PRESS_RELEASE_RESERVE_REVIEW_RESULT_REQUEST = "POST_PRESS_RELEASE_RESERVE_REVIEW_RESULT_REQUEST",
	POST_PRESS_RELEASE_RESERVE_REVIEW_RESULT_SUCCEEDED = "POST_PRESS_RELEASE_RESERVE_REVIEW_RESULT_SUCCEEDED",
	POST_PRESS_RELEASE_RESERVE_REVIEW_RESULT_FAILED = "POST_PRESS_RELEASE_RESERVE_REVIEW_RESULT_FAILED",

	SET_PRESS_RELEASE_RESERVE_AUTO_MEDIA = "SET_PRESS_RELEASE_RESERVE_AUTO_MEDIA",
}

export default PressReleaseReserveActionType

