enum InviteActionType {
	POST_INVITE_REQUEST = "POST_INVITE_REQUEST",
	POST_INVITE_SUCCEEDED = "POST_INVITE_SUCCEEDED",
	POST_INVITE_FAILED = "POST_INVITE_FAILED",
}

export default InviteActionType;

